global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'streamlit'
    static_configs:
      - targets: ['streamlit:8501']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']  # only works if MLflow is exposing /metrics

  - job_name: 'jupyter'
    static_configs:
      - targets: ['jupyter:8888']  # optional, only if instrumented

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

