name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest

    - name: Auto-format with black
      run: |
        black .  # You can add --check to fail if formatting needed

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Run unit tests
      run: |
        pytest

    - name: Build Docker image
      run: docker build -t loan-default-app .

    - name: Deploy to remote server
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.206.169.206 '
          cd loan-default-mlops &&
          git pull &&
          docker compose down &&
          docker compose up --build -d
        '

