name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run unit tests
      run: |
        pytest

    - name: Build Docker image
      run: docker build -t loan-default-app .

    - name: Deploy to remote server (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.48.138.147 '
          cd loan-default-mlops &&
          git pull &&
          docker compose down &&
          docker compose up --build -d
        '

